---
title: "data_import"
author: "Yuying Lu"
date: "2024-09-17"
output: github_document
---

```{r setup, echo = FALSE, message= FALSE}
library(tidyverse)
options(tibble.print_min=5)
```

This document will show how to tidy data.


```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()

pulse_df
```

This needs to go from wide to long format

### `pivot_longer`


```{r}
pulse_tidy_df = 
  pulse_df |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score"
  )

pulse_tidy_df
```

```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df,
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )

pulse_tidy_df
```


```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  ) |> 
  relocate(visit, .after = id)

print(pulse_df, n = 12)
```


**Learning Assessment**

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = 'gd',
    values_to = 'weight') |> 
    mutate(gd = case_match(
                gd,
                "gd0_weight"  ~ 0,
                "gd18_weight" ~ 18
                ))
litters_df
```


### `pivot_wider`

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )

analysis_result
```

```{r}
pivot_wider(
  analysis_result,
  names_from = "time",
  values_from = "mean"
) |> 
  knitr::kable() # nicer table to read
```

### Binding rows

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(movie = "return_king")
```


```{r}
lotr_tidy = bind_rows(fellowship_ring,two_towers, return_king) |> 
  janitor::clean_names() |> 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words") |> 
  mutate(race= str_to_lower(race)) |> 
  select(movie, everything())
lotr_tidy  
```



```{r}
pup_df = 
  read_csv("./data/FAS_pups.csv",
           na= c("NA", ",", ".")) |> 
  janitor::clean_names() |> 
  mutate(
    sex=
      case_match(
        sex,
        1~ "male",
        2~ "female"
      ),
    sex= as.factor(sex)
  )
pup_df
```



```{r}
litter_df = 
  read_csv("./data/FAS_litters.csv",
           na= c("NA", ",", ".")) |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day_of_tx"), sep=3) |> 
  relocate(litter_number) |> 
  mutate(
    wt_gain = gd18_weight -  gd0_weight,
    dose = str_to_lower(dose)
  )
litter_df
```

```{r}
fas_df = 
  left_join(
    pup_df, litter_df, by = "litter_number"
  )

fas_df
```

**Learning Assignment**

```{r}
df1 = read_csv("./survey_results/surv_os.csv")
df1

df2 = read_csv("./survey_results/surv_program_git.csv")
df2
```


