---
title: "Data Manupulation"
author: "Yuying Lu"
date: "2024-09-19"
output: github_document
---

```{r setup, echo = FALSE, message= FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to import *manipulate* data.

Improting the two datasets that we're going to munipulate.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "","."))
litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", "","."))
pups_df = janitor::clean_names(pups_df)
 
```


## `select`

Use `select()` to select variavles

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group:gd18_weight)
```


```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, contains("pups"))
```

Rename

```{r}
select(litters_df, GROUP = group)
```

```{r}
rename(litters_df, GROUP = group)
```

```{r}
select(litters_df, litter_number, group)
select(litters_df, litter_number, group, everything())
relocate(litters_df, litter_number, gd0_weight)
```


## `filter`

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, pups_born_alive >= 8)
filter(litters_df, pups_born_alive != 8)
```

```{r}
filter(litters_df, group == "Con7")
filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive == 8)
```


```{r}
filter(litters_df, group %in% c("Low7", "Low8") | pups_born_alive == 8)
```

Drop missing data

```{r}
drop_na(litters_df)
```

```{r}
drop_na(litters_df, gd0_weight)
```


**Exercises**

```{r}
filter(pups_df, sex==1)
```

```{r}
filter(pups_df, pd_walk < 11, sex == 2)
```


## `mutate`

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, sq_pups = pups_born_alive^2)

mutate(litters_df, group = str_to_lower(group))
```


```{r}
mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```


## `arrange`


```{r}
arrange(litters_df, gd0_weight)
```

```{r}
arrange(litters_df, desc(gd0_weight))
```


```{r}
arrange(litters_df, gd_of_birth, gd0_weight)
```


## PIPING!!!!!!!!!!!!!!!

```{r message= FALSE}
litters_df = read_csv("data/FAS_litters.csv", na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

litters_df_var = select(litters_df, -pups_born_alive)

litters_df_filter = filter(litters_df, group == 'Con7')

litters_df_mutate = mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

```

Definitely don't do this!!!

```{r}
select(janitor::clean_names(read_csv("data/FAS_litters.csv", na = c("NA", "", "."))),-pups_born_alive)
```

DO THIS:

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  select(-pups_born_alive) |>
  filter(group == "Con7") |> 
  mutate(wt_gain = gd18_weight - gd0_weight, 
         group = str_to_upper(group))
litters_df 
```

Pip with the thing

```{r}
read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  mutate(wt_gain = gd18_weight - gd0_weight) |> 
  lm(wt_gain ~ pups_born_alive, data = _)

```

Data export

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  select(-pups_born_alive) |>
  filter(group == "Con7") |> 
  mutate(wt_gain = gd18_weight - gd0_weight, 
         group = str_to_upper(group))
litters_df 

write_csv(litters_df, "data/cleaned_fas_litters.csv")
```

